### ISSUE TITLE
Subir minha plaquinha de IPTV

### ISSUE THREAD

**Issue by caloni** [Scienvitarso/lengendagem#4]

**Comment by caloni** [comment]
Tem um projeto da empresa que me permitiu ter uma dessas plaquinhas de IPTV em casa. Seria bom se a gente conseguisse brincar com ela, não?

**Comment by Scienvitarso** [comment]
Podemos, ver de integrar um tipo de shield na raspberry, já vi projetos que usam até sistema GSM, uma placa de IPTV deve ser tranquilo

**Comment by caloni** [comment]
Pois é, não manjo muito dessas plaquinhas, mas o Gianni (meu sócio) manja e
está com outra placa configurando o software que o cliente pediu. Qualquer
dúvida mais cabeluda podemos ver com ele, já que eu tenho como pendência
também fazer minha placa funcionar =)

On Wed, Aug 12, 2015 at 9:07 PM, Scienvitarso notifications@github.com
wrote:

> Podemos, ver de integrar um tipo de shield na raspberry, já vi projetos
> que usam até sistema GSM, uma placa de IPTV deve ser tranquilo
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Scienvitarso/lengendagem/issues/4#issuecomment-130487074
> .

## 

_Wanderley Caloni wanderley@caloni.com.br_http://www.caloni.com.br
http://caloni.com.br
Cel (11) 98438-5306
Work (11) 3071-1209
Skype: wanderleycaloni

-----BEGIN GEEK CODE BLOCK-----
Version: 3.1
GCS/PA d-(++) s-:(+) a C++$ UL->$ P? L+>$ !E- W++(+++)>$ N(++) o? K--?
w+++$ O? M? V? PS(+++) PE++()>$ !Y? !PGP !t 5? !X !R tv? b(+) DI+(++) D
G(+) e+ h--- r+++ y+*
------END GEEK CODE BLOCK------

**Comment by Scienvitarso** [comment]
matando 2 jacarés com um taco só
